online-shop-mvc/Areas/Admin/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Model.Entities;
using Model.Models.Request;
using Model.Models.Response;
using Model.ShopDbContext;
using online_shop_mvc.Services;
using online_shop_mvc.ServicesImp;

namespace online_shop_mvc.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ProductController : Controller
    {
        private readonly OnlineShopDbContext _onlineShopDbContext = new OnlineShopDbContext();
        private readonly IProductService _productService;
        private readonly ISizeService _sizeService;
        private readonly IColorService _colorService;
        private readonly ICategoryService _categoryService;
        private readonly IProductSizeColorService _productSizeColorService;
        public ProductController(IProductService productService, ISizeService sizeService, IColorService colorService, ICategoryService categoryService, IProductSizeColorService productSizeColorService)
        {
            _productService = productService;
            _sizeService = sizeService;
            _colorService = colorService;
            _categoryService = categoryService;
            _productSizeColorService = productSizeColorService;
        }
        public async Task<IActionResult> Index()
        {
            IList<Category> categories = await _categoryService.GetAllCategories();
            if (categories != null)
            {
                ViewBag.Categories = categories;
            }

            //Get count product
            int count = await _productService.GetCountProduct();
            ViewBag.Count = count;
            //Get all sizes
            IList<Size> sizes = await _sizeService.GetAllSizes();
            ViewBag.Sizes = sizes;
            List<SelectListItem> listSelectSizes = new List<SelectListItem>();
            foreach (var size in sizes)
            {
                SelectListItem selectList = new SelectListItem()
                {
                    Text = size.Name,
                    Value = size.Id.ToString()
                };
                listSelectSizes.Add(selectList);
                ViewBag.SizesChosen = new SelectList(listSelectSizes, "Value", "Text");
            }
            //Get all colors
            IList<Color> colors = await _colorService.GetAllColors();
            ViewBag.Colors = colors;
            List<SelectListItem> listSelectColors = new List<SelectListItem>();

            foreach (var color in colors)
            {
                SelectListItem selectList = new SelectListItem()
                {
                    Text = color.Name,
                    Value = color.Id.ToString()
                };
                listSelectColors.Add(selectList);
                ViewBag.ColorsChosen = new SelectList(listSelectColors, "Value", "Text");
            }

            return View();
        }

        [HttpPost]
        public async Task<JsonResult> handleLoadProducts()
        {
            IList<Product> product = await _productService.GetAllProductsPaging(1, 10);
            if (product != null)
            {
                return Json(new { Status = "Success", Data = product });
            }

            return Json(new { Status = "Fail", Data = "null" });
        }

        [HttpPost]
        public async Task<JsonResult> handleAddProduct(InsertProductRequestModel data)
        {
            //Product product = await _productService.Add(new Product()
            //{
            //    Name = data.Name,
            //    CategoryID = data.CategoryId,
            //    Description = data.Description,
            //    Image = data.Image,
            //    Price = data.Price
            //})

            var product = new Product()
            {
                Name = data.Name,
                CategoryID = data.CategoryId,
                Description = data.Description,
                Image = data.Image,
                Price = data.Price
            };
            await _productService.Add(product);
            if (product != null)
            {
                Console.WriteLine(product.Id);
                IList<ProductSizeColor> list = new List<ProductSizeColor>();
                foreach (var size in data.SizeId)
                {
                    foreach (var color in data.ColorId)
                    {
                        list.Add(new ProductSizeColor()
                        {
                            ProductID = 2,
                            SizeID = size,
                            ColorID = color,
                            Quantity = data.Quantity
                        });
                    }
                }
                await _onlineShopDbContext.ProductSizeColors.AddRangeAsync(list);
                await _onlineShopDbContext.SaveChangesAsync();

                //return Json(new { Status = "Success", Data = product });
            }


            return Json(new { Status = "Fail", Data = "null" });
        }

        [HttpPost]
        public async Task<JsonResult> handleEditProduct(Product data)
        {
            Product product = await _productService.Update(data);
            if (product != null)
            {
                return Json(new { Status = "Success", Data = product });
            }

            return Json(new { Status = "Fail", Data = "null" });
        }

        [HttpPost]
        public async Task<JsonResult> viewToEdit(int productId)
        {
            Product product = await _productService.GetProductById(productId);
            //Category category = await _categoryService.GetCategoryById();
            var sizes = await _productSizeColorService.GetSizeByProductId(productId);
            if(sizes != null)
            {
                foreach (var size in sizes)
                {
                    var colors = await _productSizeColorService.GetColorByProductAndSize(productId, size.Id);
                    if(colors != null)
                    {
                        foreach(var color in colors)
                        {
                            var quantity = await _productSizeColorService.GetQuantityByProductSizeColor(productId, size.Id, color.Id);
                        }
                    }
                }
            }
            //ProductResponseModel productResponse = new ProductResponseModel() 
            //{
            //    Name = product.Name,
            //    CategoryName = 

            //}


            if(product != null)
            {
                return Json(new { Status = "Success", Data = product });
            }

            return Json(new { Status = "Fail", Data = "null" });
        }
    }
}

online-shop-mvc/Controllers/CartController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis;
using Model.Entities;
using Model.Models.Request;
using Model.Models.Response;
using Model.ShopDbContext;
using Newtonsoft.Json;
using online_shop_mvc.Services;
using Repository.Repo;
using System.Data;
using System.Text.Json.Serialization;

namespace online_shop_mvc.Controllers
{
    public class CartController : Controller
    {
        private readonly IProductService _productService;
        private readonly ICategoryService _categoryService;
        private readonly IOrderService _orderService;
        private readonly IOrderDetailService _orderDetailService;
        private readonly IProductSizeColorService _productSizeColorService;
        private readonly OnlineShopDbContext _context = new OnlineShopDbContext();
        public CartController(IProductService productService, ICategoryService categoryService, IOrderService orderService, IOrderDetailService orderDetailService, IProductSizeColorService productSizeColorService)
        {
            _productService = productService;
            _categoryService = categoryService;
            _orderService = orderService;
            _orderDetailService = orderDetailService;
            _productSizeColorService = productSizeColorService;
        }
        public async Task<IActionResult> Index()
        {
            //Get all categories
            IList<Category> categories = await _categoryService.GetAllCategories();
            if (categories != null)
            {
                ViewBag.Categories = categories;
            }

            //Get order id by customer id
            Order order = await _orderService.GetOrderIdByCustomerId(1);
            if (order != null)
            {
                //Get all orders of customer
                var orderOfUser = (IList<CustomerOrderResponseModel>)await _orderDetailService.GetAllOrderDetailsByOrderId(order.Id);
                if (orderOfUser != null)
                {
                    ViewBag.OrderOfUser = orderOfUser;
                }
            }

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> HandleUserOrder()
        {
            int productID = Int32.Parse(Request.Form["product"]);
            int sizeID = Int32.Parse(Request.Form["size"]);
            int colorID = Int32.Parse(Request.Form["color"]);
            int quantity = Int32.Parse(Request.Form["quantity"]);
            int customerId = 1;
            Order order;
            DateTime dateTime = DateTime.Now;
            //Check user order
            bool check = await _orderService.CheckUserOrder(customerId);
            Console.WriteLine(check);
            if (check)
            {
                order = await _orderService.GetOrderIdByCustomerId(customerId);

                var product = (Product)await _productService.GetProductById(productID);
                decimal unitPrice = product.Price * quantity;

                if (order != null)
                {
                    var checkUserOrder = await _orderDetailService.CheckUserOrderProduct(order.Id, productID, sizeID, colorID);
                    if (checkUserOrder != null)
                    {
                        checkUserOrder.Quantity = checkUserOrder.Quantity + quantity;
                        checkUserOrder.UnitPrice = checkUserOrder.UnitPrice + product.Price;
                        var response = await _orderDetailService.Update(checkUserOrder);
                    }
                    else
                    {
                        OrderDetail orderDetail = new OrderDetail()
                        {
                            OrderId = order.Id,
                            ProductId = productID,
                            Quantity = quantity,
                            UnitPrice = unitPrice,
                            SizeId = sizeID,
                            ColorId = colorID,
                        };
                        var response = await _orderDetailService.Add(orderDetail);
                    }
                }
            }
            else
            {
                Order order1 = new Order()
                {
                    CreatedDate = dateTime,
                    CustomerId = customerId,
                };
                var test = await _orderService.Add(order1);
                order = await _orderService.GetOrderIdByCustomerId(customerId);
                var product = (Product)await _productService.GetProductById(productID);
                decimal unitPrice = product.Price * quantity;

                OrderDetail orderDetail = new OrderDetail()
                {
                    OrderId = order.Id,
                    ProductId = productID,
                    Quantity = quantity,
                    UnitPrice = unitPrice,
                    SizeId = sizeID,
                    ColorId = colorID,
                };
                var response = await _orderDetailService.Add(orderDetail);
            }

           //Handle user order product
            //customerorderrequestmodel userorder = new customerorderrequestmodel()
            //{
            //    customerid = customerid,
            //    productid = productid,
            //    createdate = datetime.now,
            //    sizeid = sizeid,
            //    colorid = colorid,
            //    quantity = quantity,
            //};
            //await _orderService.Add(userOrder);

            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<JsonResult> HandleUserOrderUpdateQuantity(CustomerUpdateQuantityModel data)
        {
            int quantity = data.Quantity;
            int orderDetailId = data.OrderDetailId;

            OrderDetail detail = await _orderDetailService.GetOrderDetailById(orderDetailId);
            int quantityProduct = await _productSizeColorService.GetQuantityByProductSizeColor(detail.ProductId, detail.SizeId, detail.ColorId);
            if (quantityProduct < quantity)
            {
                return Json(new { status = "error" ,data = "Sản phẩm vượt quá giới hạn !!!"});
            }

            OrderDetail orderDetail = new OrderDetail()
            {
                Id = orderDetailId,
                Quantity = quantity
            };
            await _orderDetailService.Update(orderDetail);

            return Json(new { status = "success", data = "" });
        }

        [HttpPost]
        public async Task<JsonResult> HandleDeleteCartItem(int orderId, int orderDetailId)
        {
            if (orderId > 0 && orderDetailId > 0)
            {
                int count = await _orderDetailService.GetCountOrderDetailsByOrderId(orderId);
                if (count == 1)
                {
                    await _orderService.Delete(orderId);
                }
                if (await _orderDetailService.Delete(orderDetailId))
                {
                    return Json(new { Status = "success", Count = count });
                }
            }

            return Json(new { Status = "fail" });
        }
    }
}

online-shop-mvc/Controllers/ContactController.cs
using Microsoft.AspNetCore.Mvc;

namespace online_shop_mvc.Controllers
{
    public class ContactController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

online-shop-mvc/Controllers/LoginController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis;
using Model.Entities;
using Model.Models.Request;
using Newtonsoft.Json;
using online_shop_mvc.Services;

namespace online_shop_mvc.Controllers
{
    public class LoginController : Controller
    {
        private readonly IAccountService accountService;
        public LoginController(IAccountService accountService)
        {
            this.accountService = accountService;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> HandleLogin(LoginRequest login)
        {
            if (login != null)
            {
                Account account = await accountService.CheckLogin(login.Username, login.Password);
                if (account != null)
                {
                    HttpContext.Session.SetString("USER_LOGIN", JsonConvert.SerializeObject(account));
                }
            }
            return RedirectToAction("Index", "Home");
        }
    }
}

online-shop-mvc/Views/Shared/_Header.cshtml
 <!-- Topbar Start -->
<div class="container-fluid">
    <div class="row bg-secondary py-1 px-xl-5">
        <div class="col-lg-6 d-none d-lg-block">
            <div class="d-inline-flex align-items-center h-100">
                <a class="text-body mr-3" href="">About</a>
                <a class="text-body mr-3" href="">Contact</a>
                <a class="text-body mr-3" href="">Help</a>
                <a class="text-body mr-3" href="">FAQs</a>
            </div>
        </div>
        <div class="col-lg-6 text-center text-lg-right">
            <div class="d-inline-flex align-items-center">
                <div class="btn-group">
                    <button type="button" class="btn btn-sm btn-light dropdown-toggle" data-toggle="dropdown">My Account</button>
                    <div class="dropdown-menu dropdown-menu-right">
                        <a class="dropdown-item" asp-controller="Login" asp-action="Index">Sign in</a>
                        <button class="dropdown-item" type="button">Sign up</button>
                    </div>
                </div>

            </div>
            <div class="d-inline-flex align-items-center d-block d-lg-none">
                <a href="" class="btn px-0 ml-2">
                    <i class="fas fa-heart text-dark"></i>
                    <span class="badge text-dark border border-dark rounded-circle" style="padding-bottom: 2px;">0</span>
                </a>
                <a href="" class="btn px-0 ml-2">
                    <i class="fas fa-shopping-cart text-dark"></i>
                    <span class="badge text-dark border border-dark rounded-circle" style="padding-bottom: 2px;">0</span>
                </a>
            </div>
        </div>
    </div>
    <div class="row align-items-center bg-light py-3 px-xl-5 d-none d-lg-flex">
        <div class="col-lg-4">
            <a href="" class="text-decoration-none">
                <span class="h1 text-uppercase text-primary bg-dark px-2">Multi</span>
                <span class="h1 text-uppercase text-dark bg-primary px-2 ml-n1">Shop</span>
            </a>
        </div>
        <div class="col-lg-4 col-6 text-left">
            <form>
                <div class="input-group">
                    <input type="text" class="form-control" id="inp-search" placeholder="Search for products">
                    <div style="submit" class="input-group-append" id="btn-search" role="button">
                        <span class="input-group-text bg-transparent text-primary">
                            <i class="fa fa-search"></i>
                        </span>
                    </div>
                </div>
            </form>
        </div>
        <div class="col-lg-4 col-6 text-right">
            <p class="m-0">Customer Service</p>
            <h5 class="m-0">+012 345 6789</h5>
        </div>
    </div>
</div>
<!-- Topbar End -->
@section scripts{
    <script type="text/javascript">

        $(document).ready(function () {
           $(document).on("click", "#btn-search", function (e) {
                console.log("hi")
                var search = $('#inp-search').val();
                console.log(search)
            });
        });
        
            
    </script>
}

online-shop-mvc/Views/Shared/_Layout.cshtml
@using Model.Entities
@using System.Collections

@{
}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>MultiShop - Online Shop Website Template</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="Free HTML Templates" name="keywords">
    <meta content="Free HTML Templates" name="description">

    <!-- Favicon -->
    <link href="~/client/img/favicon.ico" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&display=swap" rel="stylesheet">

    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="~/client/lib/animate/animate.min.css" rel="stylesheet">
    <link href="~/client/lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="~/client/css/style.css" rel="stylesheet">
    
</head>

<body>
    @*@{
    var a = (IList<Model.Entities.Category>)ViewBag.Categories;
    Console.WriteLine(a.Count());
    }*@

    <!-- Content Start -->
    @RenderBody()
    <!-- Content End -->
    <!-- Footer Start -->
    <div class="container-fluid bg-dark text-secondary mt-5 pt-5">
        <div class="row px-xl-5 pt-5">
            <div class="col-lg-4 col-md-12 mb-5 pr-3 pr-xl-5">
                <h5 class="text-secondary text-uppercase mb-4">Get In Touch</h5>
                <p class="mb-4">No dolore ipsum accusam no lorem. Invidunt sed clita kasd clita et et dolor sed dolor. Rebum tempor no vero est magna amet no</p>
                <p class="mb-2"><i class="fa fa-map-marker-alt text-primary mr-3"></i>123 Street, New York, USA</p>
                <p class="mb-2"><i class="fa fa-envelope text-primary mr-3"></i>info@example.com</p>
                <p class="mb-0"><i class="fa fa-phone-alt text-primary mr-3"></i>+012 345 67890</p>
            </div>
            <div class="col-lg-8 col-md-12">
                <div class="row">
                    <div class="col-md-4 mb-5">
                        <h5 class="text-secondary text-uppercase mb-4">Quick Shop</h5>
                        <div class="d-flex flex-column justify-content-start">
                            <a class="text-secondary mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Home</a>
                            <a class="text-secondary mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Our Shop</a>
                            <a class="text-secondary mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Shop Detail</a>
                            <a class="text-secondary mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Shopping Cart</a>
                            <a class="text-secondary mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Checkout</a>
                            <a class="text-secondary" href="#"><i class="fa fa-angle-right mr-2"></i>Contact Us</a>
                        </div>
                    </div>
                    <div class="col-md-4 mb-5">
                        <h5 class="text-secondary text-uppercase mb-4">My Account</h5>
                        <div class="d-flex flex-column justify-content-start">
                            <a class="text-secondary mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Home</a>
                            <a class="text-secondary mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Our Shop</a>
                            <a class="text-secondary mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Shop Detail</a>
                            <a class="text-secondary mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Shopping Cart</a>
                            <a class="text-secondary mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Checkout</a>
                            <a class="text-secondary" href="#"><i class="fa fa-angle-right mr-2"></i>Contact Us</a>
                        </div>
                    </div>
                    <div class="col-md-4 mb-5">
                        <h5 class="text-secondary text-uppercase mb-4">Newsletter</h5>
                        <p>Duo stet tempor ipsum sit amet magna ipsum tempor est</p>
                        <form action="">
                            <div class="input-group">
                                <input type="text" class="form-control" placeholder="Your Email Address">
                                <div class="input-group-append">
                                    <button class="btn btn-primary">Sign Up</button>
                                </div>
                            </div>
                        </form>
                        <h6 class="text-secondary text-uppercase mt-4 mb-3">Follow Us</h6>
                        <div class="d-flex">
                            <a class="btn btn-primary btn-square mr-2" href="#"><i class="fab fa-twitter"></i></a>
                            <a class="btn btn-primary btn-square mr-2" href="#"><i class="fab fa-facebook-f"></i></a>
                            <a class="btn btn-primary btn-square mr-2" href="#"><i class="fab fa-linkedin-in"></i></a>
                            <a class="btn btn-primary btn-square" href="#"><i class="fab fa-instagram"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row border-top mx-xl-5 py-4" style="border-color: rgba(256, 256, 256, .1) !important;">
            <div class="col-md-6 px-xl-0">
                <p class="mb-md-0 text-center text-md-left text-secondary">
                    &copy; <a class="text-primary" href="#">Domain</a>. All Rights Reserved. Designed
                    by
                    <a class="text-primary" href="https://htmlcodex.com">HTML Codex</a>
                </p>
            </div>
            <div class="col-md-6 px-xl-0 text-center text-md-right">
                <img class="img-fluid" src="~/client/img/payments.png" alt="">
            </div>
        </div>
    </div>
    <!-- Footer End -->
    <!-- Back to Top -->
    <a href="#" class="btn btn-primary back-to-top"><i class="fa fa-angle-double-up"></i></a>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
    <script src="~/client/lib/easing/easing.min.js"></script>
    <script src="~/client/lib/owlcarousel/owl.carousel.min.js"></script>

    <!-- Contact Javascript File -->
    <script src="~/client/mail/jqBootstrapValidation.min.js"></script>
    <script src="~/client/mail/contact.js"></script>

    <!-- Template Javascript -->
    <script src="~/client/js/main.js"></script>
    @RenderSection("scripts", required: false);
    
</body>
    
</html>

online-shop-mvc/Views/Shared/_Navbar.cshtml
@model IList<Model.Entities.Category>

@{
    
}

<!-- Navbar Start -->
<div class="container-fluid bg-dark mb-30">
    <div class="row px-xl-5">
        <div class="col-lg-3 d-none d-lg-block">
            <a class="btn d-flex align-items-center justify-content-between bg-primary w-100" data-toggle="collapse" href="#navbar-vertical" style="height: 65px; padding: 0 30px;">
                <h6 class="text-dark m-0"><i class="fa fa-bars mr-2"></i>Categories</h6>
                <i class="fa fa-angle-down text-dark"></i>
            </a>
            <nav class="collapse position-absolute navbar navbar-vertical navbar-light align-items-start p-0 bg-light" id="navbar-vertical" style="width: calc(100% - 30px); z-index: 999;">
                <div class="navbar-nav w-100">
                    @{
                        if (@Model != null)
                        {
                            foreach(var @item in @Model){
                                <a asp-controller="Product" asp-action="Category" asp-route-id="@item.Id" class="nav-item nav-link">@item.Name</a>
                            }  
                        }
                    }
                </div>
            </nav>
        </div>
        <div class="col-lg-9">
            <nav class="navbar navbar-expand-lg bg-dark navbar-dark py-3 py-lg-0 px-0">
                <a href="" class="text-decoration-none d-block d-lg-none">
                    <span class="h1 text-uppercase text-dark bg-light px-2">Multi</span>
                    <span class="h1 text-uppercase text-light bg-primary px-2 ml-n1">Shop</span>
                </a>
                <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
                    <div class="navbar-nav mr-auto py-0">
                        <a class="nav-item nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        <a class="nav-item nav-link" asp-area="" asp-controller="Product" asp-action="Index" asp-route-page="1">Product</a>
                        <div class="nav-item dropdown">
                            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">Pages <i class="fa fa-angle-down mt-1"></i></a>
                            <div class="dropdown-menu bg-primary rounded-0 border-0 m-0">
                                <a class="dropdown-item" asp-area="" asp-controller="Cart" asp-action="Index">Shopping Cart</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Checkout" asp-action="Index">Checkout</a>
                            </div>
                        </div>
                        <a class="nav-item nav-link" asp-area="" asp-controller="Contact" asp-action="Index">Contact</a>
                    </div>
                    <div class="navbar-nav ml-auto py-0 d-none d-lg-block">
                        <a href="" class="btn px-0">
                            <i class="fas fa-heart text-primary"></i>
                            <span class="badge text-secondary border border-secondary rounded-circle" style="padding-bottom: 2px;">0</span>
                        </a>
                        <a href="" class="btn px-0 ml-3">
                            <i class="fas fa-shopping-cart text-primary"></i>
                            <span class="badge text-secondary border border-secondary rounded-circle" style="padding-bottom: 2px;">0</span>
                        </a>
                    </div>
                </div>
            </nav>
        </div>
    </div>
</div>
<!-- Navbar End -->