online-shop-mvc/Areas/Admin/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using Model.Entities;
using Model.Models.Request;
using online_shop_mvc.Services;
using online_shop_mvc.ServicesImp;

namespace online_shop_mvc.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CategoryController : Controller
    {
        private readonly ICategoryService categoryService;
        public CategoryController(ICategoryService categoryService)
        {
            this.categoryService = categoryService;

        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<JsonResult> handleLoadCategories()
        {
            IList<Category> category = await categoryService.GetAllCategories();
            if (category != null)
            {
                return Json(new { Status = "Success", Data = category });
            }

            return Json(new { Status = "Fail", Data = "null" });
        }


        [HttpPost]
        public async Task<JsonResult> handleEditCategory(Category data)
        {
            Category category = await categoryService.Update(data);
            if (category != null)
            {
                return Json(new { Status = "Success", Data = category });
            }

            return Json(new { Status = "Fail", Data = "null" });
        } 

        [HttpPost]
        public async Task<JsonResult> handleAddCategory(Category data)
        {
            Category category = await categoryService.Add(data);
            if (category != null)
            {
                return Json(new { Status = "Success", Data = category });
            }

            return Json(new { Status = "Fail", Data = "null" });
        }
    }
}

online-shop-mvc/Areas/Admin/Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using Model.Entities;
using Model.Models.Response;
using online_shop_mvc.Services;
using System.Collections.Generic;

namespace online_shop_mvc.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class OrderController : Controller
    {
        private readonly IBillService _billService;
        private readonly ICustomerService _customerService;
        private readonly IBillDetailService _billDetailService;
        public OrderController(IBillService billService, ICustomerService customerService, IBillDetailService billDetailService)
        {
            _billService = billService;
            _customerService = customerService;
            _billDetailService = billDetailService;
        }

        public async Task<IActionResult> Index()
        {
            IList<Bill> bills = await _billService.GetAllBill();
            Console.WriteLine(bills);
            IList<CustomerOrderModel> billList = new List<CustomerOrderModel>();
            if (bills != null)
            {
                foreach (var item in bills)
                {
                    Customer cus = await _customerService.GetCustomerById(item.CustomerId);
                    var bill = new CustomerOrderModel()
                    {

                        BillId = item.Id,
                        CustomerName = cus.FullName,
                        Phone = cus.PhoneNumber,
                        Address = cus.Address,
                        DateCreate = item.CreatedDate.ToString(),
                        Total = item.Total,
                        EmployeeId = item.EmployeeId,
                        EmployeeName = "test",
                        Status = item.Status,

                    };
                    billList.Add(bill);
                }
                return View(billList);
            }
            return NotFound();
        }

        public async Task<IActionResult> OrderDetail(int id)
        {
            IList<CustomerOrderResponseModel> billDetail = await _billDetailService.GetAllBillDetailsByBillId(id);
            if (billDetail == null)
            {
                return NotFound();
            }
            return View(billDetail);
        }

        [HttpPost]
        public async Task<JsonResult> handleLoadOrders()
        {
            //IList<Order> orders = await orderService.GetAllOrders();
            //if (orders != null)
            //{
            //    return Json(new { Status = "Success", Data = orders });
            //}

            return Json(new { Status = "Fail", Data = "null" });
        }


        [HttpPost]
        public async Task<JsonResult> handleConfirmOrder(int orderId, int status)
        {
            //Order order = await orderService.Update(data);
            //if (order != null)
            //{
            //    return Json(new { Status = "Success", Data = order });
            //}

            return Json(new { Status = "Fail", Data = "null" });
        }

        [HttpGet]
        public async Task<IActionResult> HandleUpdateStatusBill()
        {
            int status = Int32.Parse(Request.Query["status"]);
            int billId = Int32.Parse(Request.Query["billid"]);
            await _billService.UpdateStatus(billId, status);
            return RedirectToAction("Index");
        }
    }
}

online-shop-mvc/Areas/Admin/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Model.Entities;
using Model.Models.Request;
using Model.Models.Response;
using Model.ShopDbContext;
using online_shop_mvc.Services;
using online_shop_mvc.ServicesImp;

namespace online_shop_mvc.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ProductController : Controller
    {
        private readonly OnlineShopDbContext _onlineShopDbContext = new OnlineShopDbContext();
        private readonly IProductService _productService;
        private readonly ISizeService _sizeService;
        private readonly IColorService _colorService;
        private readonly ICategoryService _categoryService;
        private readonly IProductSizeColorService _productSizeColorService;
        public ProductController(IProductService productService, ISizeService sizeService, IColorService colorService, ICategoryService categoryService, IProductSizeColorService productSizeColorService)
        {
            _productService = productService;
            _sizeService = sizeService;
            _colorService = colorService;
            _categoryService = categoryService;
            _productSizeColorService = productSizeColorService;
        }
        public async Task<IActionResult> Index()
        {
            IList<Category> categories = await _categoryService.GetAllCategories();
            if (categories != null)
            {
                ViewBag.Categories = categories;
            }

            //Get count product
            int count = await _productService.GetCountProduct();
            ViewBag.Count = count;
            //Get all sizes
            IList<Size> sizes = await _sizeService.GetAllSizes();
            ViewBag.Sizes = sizes;
            List<SelectListItem> listSelectSizes = new List<SelectListItem>();
            foreach (var size in sizes)
            {
                SelectListItem selectList = new SelectListItem()
                {
                    Text = size.Name,
                    Value = size.Id.ToString()
                };
                listSelectSizes.Add(selectList);
                ViewBag.SizesChosen = new SelectList(listSelectSizes, "Value", "Text");
            }
            //Get all colors
            IList<Color> colors = await _colorService.GetAllColors();
            ViewBag.Colors = colors;
            List<SelectListItem> listSelectColors = new List<SelectListItem>();

            foreach (var color in colors)
            {
                SelectListItem selectList = new SelectListItem()
                {
                    Text = color.Name,
                    Value = color.Id.ToString()
                };
                listSelectColors.Add(selectList);
                ViewBag.ColorsChosen = new SelectList(listSelectColors, "Value", "Text");
            }

            return View();
        }

        [HttpPost]
        public async Task<JsonResult> handleLoadProducts()
        {
            IList<Product> product = await _productService.GetAllProductsPaging(1, 10);
            if (product != null)
            {
                return Json(new { Status = "Success", Data = product });
            }

            return Json(new { Status = "Fail", Data = "null" });
        }

        [HttpPost]
        public async Task<JsonResult> handleAddProduct(InsertProductRequestModel data)
        {
            //Product product = await _productService.Add(new Product()
            //{
            //    Name = data.Name,
            //    CategoryID = data.CategoryId,
            //    Description = data.Description,
            //    Image = data.Image,
            //    Price = data.Price
            //})

            var product = new Product()
            {
                Name = data.Name,
                CategoryID = data.CategoryId,
                Description = data.Description,
                Image = data.Image,
                Price = data.Price
            };
            await _productService.Add(product);
            if (product != null)
            {
                Console.WriteLine(product.Id);
                IList<ProductSizeColor> list = new List<ProductSizeColor>();
                foreach (var size in data.SizeId)
                {
                    foreach (var color in data.ColorId)
                    {
                        list.Add(new ProductSizeColor()
                        {
                            ProductID = 2,
                            SizeID = size,
                            ColorID = color,
                            Quantity = data.Quantity
                        });
                    }
                }
                await _onlineShopDbContext.ProductSizeColors.AddRangeAsync(list);
                await _onlineShopDbContext.SaveChangesAsync();

                //return Json(new { Status = "Success", Data = product });
            }


            return Json(new { Status = "Fail", Data = "null" });
        }

        [HttpPost]
        public async Task<JsonResult> handleEditProduct(Product data)
        {
            Product product = await _productService.Update(data);
            if (product != null)
            {
                return Json(new { Status = "Success", Data = product });
            }

            return Json(new { Status = "Fail", Data = "null" });
        }

        [HttpPost]
        public async Task<JsonResult> viewToEdit(int productId)
        {
            Product product = await _productService.GetProductById(productId);
            //Category category = await _categoryService.GetCategoryById();
            var sizes = await _productSizeColorService.GetSizeByProductId(productId);
            if(sizes != null)
            {
                foreach (var size in sizes)
                {
                    var colors = await _productSizeColorService.GetColorByProductAndSize(productId, size.Id);
                    if(colors != null)
                    {
                        foreach(var color in colors)
                        {
                            var quantity = await _productSizeColorService.GetQuantityByProductSizeColor(productId, size.Id, color.Id);
                        }
                    }
                }
            }
            //ProductResponseModel productResponse = new ProductResponseModel() 
            //{
            //    Name = product.Name,
            //    CategoryName = 

            //}


            if(product != null)
            {
                return Json(new { Status = "Success", Data = product });
            }

            return Json(new { Status = "Fail", Data = "null" });
        }
    }
}

online-shop-mvc/Areas/Admin/Controllers/SizeController.cs
using Microsoft.AspNetCore.Mvc;
using Model.Entities;
using online_shop_mvc.Services;
using online_shop_mvc.ServicesImp;

namespace online_shop_mvc.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class SizeController : Controller
    {
        private readonly ISizeService sizeService;
        public SizeController(ISizeService sizeService)
        {
            this.sizeService = sizeService;

        }
        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public async Task<JsonResult> handleLoadSizes()
        {
            IList<Size> size = await sizeService.GetAllSizes();
            if (size != null)
            {
                return Json(new { Status = "Success", Data = size });
            }

            return Json(new { Status = "Fail", Data = "null" });
        }


        [HttpPost]
        public async Task<JsonResult> handleEditSize(Size data)
        {
            Size size = await sizeService.Update(data);
            if (size != null)
            {
                return Json(new { Status = "Success", Data = size });
            }

            return Json(new { Status = "Fail", Data = "null" });
        }

        [HttpPost]
        public async Task<JsonResult> handleAddSize(Size data)
        {
            Size size = await sizeService.Add(data);
            if (size != null)
            {
                return Json(new { Status = "Success", Data = size });
            }

            return Json(new { Status = "Fail", Data = "null" });
        }
    }
}

online-shop-mvc/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>DarkPan - Bootstrap 5 Admin Template</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport" />
    <meta content="" name="keywords" />
    <meta content="" name="description" />

    <!-- Favicon -->
    <link href="~/Admin/img/favicon.ico" rel="icon" />

    @*JQuery Chosen*@
    <link href="https://cdnjs.cloudflare.com/ajax/libs/chosen/1.8.7/chosen.min.css" rel="stylesheet" />

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;600&family=Roboto:wght@500;700&display=swap"
          rel="stylesheet" />

    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css"
          rel="stylesheet" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css"
          rel="stylesheet" />

    <!-- Libraries Stylesheet -->
    <link href="~/Admin/lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet" />
    <link href="~/Admin/lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css"
          rel="stylesheet" />

    <!-- Customized Bootstrap Stylesheet -->
    <link href="~/Admin/css/bootstrap.min.css" rel="stylesheet" />

    <!-- Template Stylesheet -->
    <link href="~/Admin/css/style.css" rel="stylesheet" />



</head>

<body>
    <div class="container-fluid position-relative d-flex p-0">
        <!-- Spinner Start -->
        <div id="spinner"
             class="show bg-dark position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
            <div class="spinner-border text-primary"
                 style="width: 3rem; height: 3rem"
                 role="status">
                <span class="sr-only">Loading...</span>
            </div>
        </div>
        <!-- Spinner End -->
        <!-- Sidebar Start -->
        <div class="sidebar pe-4 pb-3">
            <nav class="navbar bg-secondary navbar-dark">
                <a href="index.html" class="navbar-brand mx-4 mb-3">
                    <h3 class="text-primary">
                        <i class="fa fa-user-edit me-2"></i>DarkPan
                    </h3>
                </a>
                <div class="d-flex align-items-center ms-4 mb-4">
                    <div class="position-relative">
                        <img class="rounded-circle"
                             src="~/Admin/img/user.jpg"
                             alt=""
                             style="width: 40px; height: 40px" />
                        <div class="bg-success rounded-circle border border-2 border-white position-absolute end-0 bottom-0 p-1"></div>
                    </div>
                    <div class="ms-3">
                        <h6 class="mb-0">Jhon Doe</h6>
                        <span>Admin</span>
                    </div>
                </div>
                <div class="navbar-nav w-100">
                    <a asp-controller="Home" asp-action="Index" class="nav-item nav-link active"><i class="fa fa-tachometer-alt me-2"></i>Thống kê</a>
                    <div class="nav-item dropdown">
                        <a href="#"
                           class="nav-link dropdown-toggle"
                           data-bs-toggle="dropdown"><i class="fa fa-laptop me-2"></i>Sản Phẩm</a>
                        <div class="dropdown-menu bg-transparent border-0">
                            <a asp-controller="Product" asp-action="Index" class="dropdown-item">Quàn lý sản Phẩm</a>
                            <a asp-controller="Category" asp-action="Index" class="dropdown-item">Loại Sản Phẩm</a>
                            <a asp-controller="Color" asp-action="Index" class="dropdown-item">Màu Sản Phẩm</a>
                            <a asp-controller="Size" asp-action="Index" class="dropdown-item">Size Sản Phẩm</a>
                        </div>
                    </div>
                    <a asp-controller="Order" asp-action="Index" class="nav-item nav-link"><i class="fa fa-th me-2"></i>Hóa Đơn</a>
                    <a href="form.html" class="nav-item nav-link"><i class="fa fa-keyboard me-2"></i>Nhân Viên</a>
                    <a href="table.html" class="nav-item nav-link"><i class="fa fa-table me-2"></i>Khách Hàng</a>
                    @*<div class="nav-item dropdown">
                    <a href="#"
                    class="nav-link dropdown-toggle"
                    data-bs-toggle="dropdown"><i class="far fa-file-alt me-2"></i>Pages</a>
                    <div class="dropdown-menu bg-transparent border-0">
                    <a href="signin.html" class="dropdown-item">Sign In</a>
                    <a href="signup.html" class="dropdown-item">Sign Up</a>
                    <a href="404.html" class="dropdown-item">404 Error</a>
                    <a href="blank.html" class="dropdown-item">Blank Page</a>
                    </div>
                    </div>*@
                </div>
            </nav>
        </div>
        <!-- Sidebar End -->
        <!-- Content Start -->
        @RenderBody()
        <!-- Content End -->
        <!-- Back to Top -->
        <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top">
            <i class="bi bi-arrow-up"></i>
        </a>
    </div>

    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/Admin/lib/chart/chart.min.js"></script>
    <script src="~/Admin/lib/easing/easing.min.js"></script>
    <script src="~/Admin/lib/waypoints/waypoints.min.js"></script>
    <script src="~/Admin/lib/owlcarousel/owl.carousel.min.js"></script>
    <script src="~/Admin/lib/tempusdominus/js/moment.min.js"></script>
    <script src="~/Admin/lib/tempusdominus/js/moment-timezone.min.js"></script>
    <script src="~/Admin/lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js"></script>


    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    @*<script src="http://code.jquery.com/jquery-latest.js"></script>*@
    <script src="https://cdnjs.cloudflare.com/ajax/libs/chosen/1.8.7/chosen.jquery.min.js"></script>



    <!-- Template Javascript -->
    <script src="~/Admin/js/main.js"></script>
</body>
</html>